apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.istiovs.name}}
  labels:
    app: {{.Values.istiovs.name}}
spec:
  hosts: 
    - "*"
  gateways: [{{.Values.istiogw.name}}]
  http:
    - name: primary
      route:
        - destination:
            host: {{.Values.webservice.name}}
          weight: {{.Values.istiovs.weight}}
        - destination:
            host: {{.Values.istiovs.weight2}}
          weight: 20