apiVersion: v1
kind: Service
metadata:
  name: {{.Values.webservice.name}}
spec:
  selector:
    app: {{.Values.webdeployment.name}}
  type: {{.Values.webservice.type}}
  ports:
    - port: {{.Values.webservice.port}}
      targetPort: {{.Values.webservice.targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.webservice.name2}}
spec:
  selector:
    app: {{.Values.webdeployment.name}}
  type: {{.Values.webservice.type2}}
  ports:
    - port: {{.Values.webservice.port}}
      targetPort: {{.Values.webservice.targetPort}}