apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  # trigger.on-deployed: |
  #   when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  service.webhook.github: |
    url: http://3.140.197.108:8080/build?token=tfs123
    basicAuth:
      username: wahaj
      password: wahaj
type: Opaque