# apiVersion: batch/v1
# kind: Pod
# metadata:
#   name: jenkins-trigger
#   annotations:
#     # argocd.argoproj.io/hook: Sync
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
# spec:
#   template:
#     spec:
#       containers:
#       - name: jenkins-job-trigger
#         image: curlimages/curl
#         command:
#           - "curl"
#           - "-I"
#           - "-u"
#           - "wahaj:wahaj"
#           - "http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123"
#       restartPolicy: Never
#   backoffLimit: 2


apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: jenkins
      url: http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123
      basicAuth:
        username: wahaj
        password: wahaj

type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      - name: on-sync-succeeded
        enabled: true
    templates:
    - name: jenkins
      webhook:
        jenkins:
          method: POST 

# # - name: sync-operation-failed
# #         condition: app.status.operationState.phase in ['Error', 'Failed']
# #         template: sync-operation-status-change
# #       - name: sync-operation-succeeded
# #         condition: app.status.operationState.phase in ['Succeeded']
# #         template: sync-operation-status-change
# #       - name: sync-operation-running
# #         condition: app.status.operationState.phase in ['Running']
# #         template: sync-operation-status-change