apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins-trigger
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: jenkins-job-trigger
        image: curlimages/curl
        command:
          - "curl"
          - "-I"
          - "-u"
          - "wahaj:wahaj"
          - "http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123"
      restartPolicy: Never
  backoffLimit: 2