apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: jenkins
      url: http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123
      basicAuth:
        username: wahaj
        password: wahaj

type: Opaque
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
 triggers:
      - name: on-sync-succeeded
        condition: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy'
        enabled: true
      - name: jenkins
        condition: app.status.operationState.phase == 'Succeeded' and app.status.health.status == 'Healthy'
        enabled: true
        template: jenkins
      - name: on-sync-failed
        enabled: true
      - name: on-sync-running
        condition: app.status.health.status == 'Progressing'
        enabled: true
  subscriptions:
  - recipients:
    - webhook:jenkins
    trigger: jenkins
  templates:
  - name: jenkins
    webhook:
      jenkins:
        method: POST
# # type: Opaque