apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: jenkins
      url: http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123
      basicAuth:
        username: wahaj
        password: wahaj

type: Opaque
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  templates:
  - name: jenkins
    webhook:
      jenkins:
        method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    recipients.argocd-notifications.argoproj.io: webhook:jenkins
  name: web