apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins-trigger
  annotations:
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: jenkins-job-trigger
        image: curlimages/curl
        command:
          - "curl"
          - "-I"
          - "-u"
          - "hamza:hamza123a"
          - "https://cmpdevops.visionet.com/job/load_testing/build?token=load_testing_123"
      restartPolicy: Never
  backoffLimit: 2
