apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    webhook:
    - name: jenkins
      url: http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123
      basicAuth:
        username: wahaj
        password: wahaj

type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  config.yaml: |
    triggers:
      - name: sync-operation-failed
        condition: app.status.operationState.phase in ['Error', 'Failed']
        template: sync-operation-status-change
      - name: sync-operation-succeeded
        condition: app.status.operationState.phase in ['Succeeded']
        template: sync-operation-status-change
      - name: sync-operation-running
        condition: app.status.operationState.phase in ['Running']
        template: sync-operation-status-change
    templates:
    - name: jenkins
      webhook:
        jenkins:
          method: POST 
          path: http://3.140.197.108:8080/job/TFS-Repo-clone/build?token=tfs123