apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-test
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000