# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
dbservice:
  type: ClusterIP
  port: 3306

dbdeployment:
    name: db
    replicas: 1
    image: mysql:8.0
    containers:
      args:
        - --default_authentication_plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      env:
        - name: MYSQL_DATABASE
          value: flaskshop
        - name: MYSQL_ROOT_PASSWORD
          value: root
    containerPort: 3306
    volumeMounts:
      - name: db-data
        mountPath: /var/lib/mysql
    volumes:
      - name: db-data
        persistentVolumeClaim: db-data
webdeployment:
  name: web
  replicas: 4
  image: 947743271187.dkr.ecr.us-east-2.amazonaws.com/flask_app:latest
  containerPort: 5000
webservice:
  name: web-service
  type: LoadBalancer
  port: 5000
  targetPort: 5000
  name2: web-test
  type2: LoadBalancer